//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obit_manager_config.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://corretto.aws/downloads/latest/amazon-corretto-8-x64-windows-jre.zip")]
        public string Jdk64bitURL {
            get {
                return ((string)(this["Jdk64bitURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://corretto.aws/downloads/latest/amazon-corretto-8-x86-windows-jre.zip")]
        public string Jdk32bitURL {
            get {
                return ((string)(this["Jdk32bitURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://corretto.aws/downloads/latest_checksum/amazon-corretto-8-x64-windows-jre." +
            "zip")]
        public string Jdk64bitMD5URL {
            get {
                return ((string)(this["Jdk64bitMD5URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://corretto.aws/downloads/latest_checksum/amazon-corretto-8-x86-windows-jre." +
            "zip")]
        public string Jdk32bitMD5URL {
            get {
                return ((string)(this["Jdk32bitMD5URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/aarpon/obit_datamover_jsl/archive/0.2.0.zip")]
        public string DatamoverJslURL {
            get {
                return ((string)(this["DatamoverJslURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wiki-bsse.ethz.ch/download/attachments/21567716/datamover-15.06.0-r34542." +
            "zip")]
        public string DatamoverURL {
            get {
                return ((string)(this["DatamoverURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/aarpon/obit_annotation_tool/releases/download/2.1.0/obit_annot" +
            "ation_tool_2.1.0_64bit.zip")]
        public string AnnotationTool64bitURL {
            get {
                return ((string)(this["AnnotationTool64bitURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/aarpon/obit_annotation_tool/releases/download/2.1.0/obit_annot" +
            "ation_tool_2.1.0_32bit.zip")]
        public string AnnotationTool32bitURL {
            get {
                return ((string)(this["AnnotationTool32bitURL"]));
            }
        }
    }
}
